# Generated by Django 4.2.5 on 2023-09-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_on',
            new_name='added_on',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='created_on',
            new_name='added_on',
        ),
    ]
